### ISSUE TITLE
pg-promise hint

### ISSUE THREAD

**Issue by vitaly-t** [xiaofan2406/pglize#1]
Are you familiar with the types and methods within the [helpers](http://vitaly-t.github.io/pg-promise/helpers.html) namespace?

You seem to be re-doing quite a bit of what is already there. :wink:

**Comment by xiaofan2406** [comment]
@vitaly-t woah, where did this documentation comes from? I have only been accessing the docs on the github repo.

**Comment by xiaofan2406** [comment]
@vitaly-t I just realized that you are the author of `pg-promise`.  great docs. 👍
